version: '3.4'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     # provide your credentials here
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INTIDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express  
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb